#!/usr/bin/env bash
# Build the chess engine WASM module and create a distributable zip package.
#
# Stage 1 – Build: compiles the Rust crate to WASM via wasm-pack.
# Stage 2 – Package: bundles viewer + WASM into a dated archive that anyone
#            can extract and run locally with a simple HTTP server.
#
# Usage: ./package.sh
#
# Prerequisites (one-time setup):
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-pack
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Stage 1: Build ──────────────────────────────────────────────────────────
echo "==> Stage 1: Building WASM module"
./build.sh

# ── Stage 2: Package ────────────────────────────────────────────────────────
VERSION="$(date +%Y%m%d)"
PACKAGE_NAME="grandmaster-chess-ai-${VERSION}"
echo "==> Stage 2: Packaging ${PACKAGE_NAME}.zip"

rm -rf "${PACKAGE_NAME}"
mkdir -p "${PACKAGE_NAME}/pkg"

# Viewer HTML
cp index.html "${PACKAGE_NAME}/"

# WASM binaries and JS glue (generated by wasm-pack)
cp pkg/chess_engine.js           "${PACKAGE_NAME}/pkg/"
cp pkg/chess_engine_bg.wasm      "${PACKAGE_NAME}/pkg/"
cp pkg/chess_engine.d.ts         "${PACKAGE_NAME}/pkg/"
cp pkg/chess_engine_bg.wasm.d.ts "${PACKAGE_NAME}/pkg/"
cp pkg/package.json              "${PACKAGE_NAME}/pkg/"

# Verify package manifest before archiving.
REQUIRED_FILES=(
    "${PACKAGE_NAME}/index.html"
    "${PACKAGE_NAME}/pkg/chess_engine.js"
    "${PACKAGE_NAME}/pkg/chess_engine_bg.wasm"
    "${PACKAGE_NAME}/pkg/chess_engine.d.ts"
    "${PACKAGE_NAME}/pkg/chess_engine_bg.wasm.d.ts"
    "${PACKAGE_NAME}/pkg/package.json"
)

for f in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$f" ]; then
        echo "Missing required package file: $f"
        exit 1
    fi
done

# ── start-server.sh (Linux / macOS) ─────────────────────────────────────────
cat > "${PACKAGE_NAME}/start-server.sh" << 'EOF'
#!/usr/bin/env bash
# Serve the chess WASM viewer over HTTP.
# WASM ES-module imports require HTTP — opening index.html directly won't work.
PORT="${1:-8000}"
echo "Starting server at http://localhost:${PORT}"
echo "Open that URL in any modern browser (Chrome, Firefox, Safari, Edge)."
echo "Press Ctrl+C to stop."
cd "$(dirname "$0")"
if command -v python3 &>/dev/null; then
    python3 -m http.server "${PORT}"
elif command -v python &>/dev/null; then
    python -m http.server "${PORT}"
else
    echo "Python not found. Serve this directory with any HTTP server, e.g.:"
    echo "  npx serve ."
    echo "  php -S localhost:${PORT}"
    exit 1
fi
EOF
chmod +x "${PACKAGE_NAME}/start-server.sh"

# ── start-server.bat (Windows cmd) ──────────────────────────────────────────
cat > "${PACKAGE_NAME}/start-server.bat" << 'EOF'
@echo off
set PORT=8000
if not "%~1"=="" set PORT=%~1
echo Starting server at http://localhost:%PORT%
echo Open that URL in any modern browser (Chrome, Firefox, Safari, Edge).
echo Press Ctrl+C to stop.
cd /d "%~dp0"
python -m http.server %PORT%
if errorlevel 1 (
    echo Python not found. Serve this directory with any HTTP server, e.g.:
    echo   npx serve .
    pause
)
EOF

# ── start-server.ps1 (Windows PowerShell) ────────────────────────────────────
cat > "${PACKAGE_NAME}/start-server.ps1" << 'EOF'
param([int]$Port = 8000)
Set-Location $PSScriptRoot
Write-Host "Starting server at http://localhost:$Port"
Write-Host "Open that URL in any modern browser (Chrome, Firefox, Safari, Edge)."
Write-Host "Press Ctrl+C to stop."
if (Get-Command python3 -ErrorAction SilentlyContinue) {
    python3 -m http.server $Port
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    python -m http.server $Port
} else {
    Write-Host "Python not found. Serve this directory with any HTTP server, e.g.:"
    Write-Host "  npx serve ."
}
EOF

# ── Create archive ────────────────────────────────────────────────────────────
if command -v zip &>/dev/null; then
    zip -r "${PACKAGE_NAME}.zip" "${PACKAGE_NAME}"
    echo "Created ${PACKAGE_NAME}.zip"
else
    tar czf "${PACKAGE_NAME}.tar.gz" "${PACKAGE_NAME}"
    echo "Created ${PACKAGE_NAME}.tar.gz"
fi

rm -rf "${PACKAGE_NAME}"

echo ""
echo "Done. Distribute the archive."
echo "Recipients: extract the archive, then run start-server.sh / .bat / .ps1"
echo "and open http://localhost:8000 in any modern browser."
